import './globals.css'
import { Inter } from 'next/font/google'
import Header from './common/Header'
import Footer from './common/Footer'
import Head from './common/Head'
import "@fortawesome/fontawesome-svg-core/styles.css";



// const inter = Inter({ subsets: ['latin'] })
// layout fichier principale

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
    
    <Head/>
      <body >
      <Header/>
      {children} 
      
      <Footer/>
      </body>
    </html>
  )
}
