import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./common/Header";
import Footer from "./common/Footer";
import Head from "./common/Head";
import Provider from "@/context/Provider";
import ToasterContext from "@/context/ToasterContext";
import Script from "next/script";

// const inter = Inter({ subsets: ['latin'] })
// layout fichier principale

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Provider>
        <body>
          <ToasterContext />
          <Header />
          {/* toute les pages qui viennent apres */}
          {children}
          <Footer />

          <Script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossOrigin="anonymous "
          />
        </body>
      </Provider>
    </html>
  );
}
